export let frases = [
  "I study mathematics. 😊",
  "You work hard. 😅",
  "She loves chocolate. 🍫❤️",
  "He closes the door. 🚪",
  "They travel often. 🌍✈️",
  "We live in a big city. 🏙️",
  "You open the book. 📖",
  "I see a rainbow. 🌈",
  "She comes home early. 🏡",
  "He goes to the gym. 💪",
  "They know the answer. 🧠❓",
  "We start the project. 🚀",
  "You finish your meal. 🍽️",
  "He says hello. 👋",
  "I buy groceries. 🛒",
  "They drink coffee. ☕",
  "She eats sushi. 🍣",
  "We feel happy. 😃",
  "You fly to Paris. ✈️🗼",
  "I forget his name. 🤔",
  "She gives a gift. 🎁",
  "He hears music. 🎵",
  "They lose the game. 😔",
  "We ask a question. ❓",
  "You answer the phone. 📞",
  "She helps a friend. 🤝",
  "He takes a photo. 📸",
  "They pay the bill. 💵",
  "I sleep peacefully. 😴",
  "She speaks Spanish. 🇪🇸",
  "We make a cake. 🍰",
  "You find a key. 🔑",
  "He thinks deeply. 💭",
  "They tell a story. 📖🗣️",
  "We show a magic trick. 🎩✨",
  "You leave the party. 🎉👋",
  "She puts on her coat. 🧥",
  "He brings flowers. 💐",
  "They begin the race. 🏁🏃‍♂️",
  "I write a letter. 📝",
  "You run quickly. 🏃‍♀️🏃‍♂️",
  "She sits on the bench. 🪑",
  "He reads a novel. 📚",
  "They grow vegetables. 🌱🥕",
  "We understand the problem. 🤔💡",
  "You look beautiful. 💁‍♀️💅",
  "She turns on the light. 💡"
];

